import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div
          className={`relative h-full w-full flex justify-center items-center ${inter.className}`}
        >
          <div className="flex flex-col shadow-2xl p-4 w-[798px] mx-auto rounded-lg">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
